### ISSUE TITLE
Unable to access stomp on server after enabling rabbitmq_web_stomp plugin

### ISSUE THREAD

**Issue by sadjunky** [rabbitmq/rabbitmq-web-stomp#111]
@michaelklishin 

I have enabled **rabbitmq_web_stomp** on the RabbitMQ server. The logs show that a port number of **15674** has been opened, but it says **404** when I try to reach it through _http://hostname:15674/stomp_. The Ports and Contexts section of the Management UI shows 
<img width="246" alt="Screen Shot 2019-04-06 at 10 10 28 AM" src="https://user-images.githubusercontent.com/25087039/55664940-3fa84400-5854-11e9-8ab8-827aabb8eea2.png">
where http/web-stomp is shown. The Web Context shows 
<img width="508" alt="Screen Shot 2019-04-06 at 10 12 05 AM" src="https://user-images.githubusercontent.com/25087039/55664951-754d2d00-5854-11e9-855b-ea36111166bf.png">
This is confusing as the ports and contexts are open but yet I'm not able to access the port anywhere.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I cannot suggest much as you haven't provided any example code. This plugin comes [with a few example applications](https://github.com/rabbitmq/rabbitmq-web-stomp-examples) that you can enabled as a separate plugin, try and inspect. They use a STOMP-over-WebSockets client to access the endpoint. Regular HTTP client or Web browser won't do.

**Comment by lukebakken** [comment]
Please see [my response](https://groups.google.com/d/msg/rabbitmq-users/cWoWaVYduqg/f8e-Ifa4BAAJ).
