### ISSUE TITLE
cowboy respond with 400 bad request

### ISSUE THREAD

**Issue by gtors** [rabbitmq/rabbitmq-web-stomp#128]
Environment:
```
ubuntu 18.04
erlang 23.0
rabbitmq 3.8.5
```

`rabbitmq_web_stomp` plugin enabled with default configuration

HTTP flow from Wireshark:
```
GET /ws/ HTTP/1.1
Connection: upgrade
Host: 127.0.0.1:15674
X-Forwarded-For: 5.101.18.47
X-Real-IP: 5.101.18.47
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: Ie54zxfIoLus/Rk8k6njPA==
Pragma: no-cache
Cache-Control: no-cache

HTTP/1.1 400 Bad Request
content-length: 0
date: Fri, 10 Jul 2020 11:46:00 GMT
server: Cowboy
```

Log files doesn't contain any useful information. How to debug rabbitmq-web-stomp/cowboy?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@essen sorry to bug you but is there a debug log for Cowboy these days? Anything in this request that may stand out to you?
