### ISSUE TITLE
Improvement: document /stomp/websocket endpoint

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-web-stomp#26]
At https://www.rabbitmq.com/web-stomp.html#usage , the documentation correctly indicates that a SocksJS STOMP endpoint is exposed at /stomp . 

It would be an excellent improvement in documentation to indicate that in addition to this endpoint, STOMP over WebSocket is exposed at /stomp/websocket for WebSocket STOMP clients other than SocksJS.

**Comment by essen** [comment]
In 3.6.0, we are adding an endpoint at /ws (IIRC) that not only is just STOMP over WebSocket, but also allows you to use binary frames rather than UTF-8 text frames as it is currently impossible to transmit binary data.

You can already try it by using the current master of this plugin. Feedback welcome!

**Comment by spatula75** [comment]
I'll try to have a look soon. We will likely postpone the feature for which
we are using the plugin until 3.6 anyway because of other issues that are
apparently also fixed in 3.6.

Binary won't affect use since our objects are all serialized as JSON.

Will give it a shot and see how it works for us anyway.

**Comment by michaelklishin** [comment]
The `/ws` endpoint has been documented in master.
